Added current context view
sozercan/kubectl-ai pull request #79
Opened 2023-08-03 11:30 UTC by eyal-solomon1

* Added a small context identifier (was a bit confused on where it would be applied to)

<img width="889" alt="Screenshot 2023-07-08 at 13 07 47" src="https://github.com/sozercan/kubectl-ai/assets/74238936/6457e4e6-0b27-43e3-add5-f1b06638be41">

2023-08-04 05:11 UTC, sozercan commented on .DS_Store
looks like accidentally checked in, please remove

2023-08-04 05:14 UTC, sozercan commented on cmd/cli/kubernetes.go
> +	var kubeConfig string = getKubeConfig()
```suggestion
	kubeConfig := getKubeConfig()
```

2023-08-04 05:18 UTC, sozercan requested changes
thanks! added minor comments and please address the lint errors, otherwise LGTM

2023-08-04 13:32 UTC, eyal-solomon1 commented
@sozercan fixed :)

2023-08-13 00:05 UTC, sozercan approved these changes
Thank you! LGTM

2023-08-13 00:05 UTC, merged